version: '3.8'

services:

  front:
    image: shureck/buildings-front
    restart: always
    command: pnpm run dev --host 0.0.0.0
    ports:
      - 3000:8080
    environment:
      - VITE_APP_API_BASE_URL=/api
      - VITE_APP_API_PROTOCOL=http
      - VITE_APP_API_HOST=62.109.26.235
      - VITE_APP_API_SERVICE_PORT=8180
      - VITE_APP_MAPBOX_SECRET_ACCESS_TOKEN=<>
      - VITE_APP_MAPBOX_PUBLIC_ACCESS_TOKEN=<>
  web:
    image: shureck/buildings-back
    restart: always
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8180:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:11.11
    volumes:
      - ./db/:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=shureck
      - POSTGRES_PASSWORD=787898QWEqwe
      - POSTGRES_DB=biji